### ISSUE TITLE
Enhance The phrase "Enter your mail here" 

### ISSUE THREAD

**Issue by wgeenath** [divyaagrawal261/Corporate-Thaali#9]
Expected:
Enter your Email here

Actual:
Enter your mail here

<img width="873" alt="QA1728528725" src="https://github.com/user-attachments/assets/a09e19c4-ef43-44e3-bc4f-cb3feb1ceeb9">

This makes it clearer that users should provide their email address rather than a physical mailing address.

Kindly assign me to fix this

**Comment by divyaagrawal261** [comment]
Sorry buddy, but that's not an issue!
